// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Counter, CounterTableId } from "./tables/Counter.sol";
import { Commitment, CommitmentTableId } from "./tables/Commitment.sol";
import { Description, DescriptionTableId } from "./tables/Description.sol";
import { Deadline, DeadlineTableId } from "./tables/Deadline.sol";
import { Active, ActiveTableId } from "./tables/Active.sol";
