// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Commitment, CommitmentData, CommitmentTableId } from "./tables/Commitment.sol";
import { TaskDescription, TaskDescriptionTableId } from "./tables/TaskDescription.sol";
import { FirstCommitment, FirstCommitmentTableId } from "./tables/FirstCommitment.sol";
import { Deadline, DeadlineTableId } from "./tables/Deadline.sol";
import { ProofRequirement, ProofRequirementTableId } from "./tables/ProofRequirement.sol";
import { ProofURI, ProofURITableId } from "./tables/ProofURI.sol";
import { ProofDescription, ProofDescriptionTableId } from "./tables/ProofDescription.sol";
import { Ratings, RatingsTableId } from "./tables/Ratings.sol";
import { Attestations, AttestationsTableId } from "./tables/Attestations.sol";
import { Reputation, ReputationTableId } from "./tables/Reputation.sol";
