// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */
enum CommitmentStatus {
  Inactive,
  Active,
  Complete,
  Failed
}

enum ProofType {
  None,
  Photo
}

enum ProgressionZone {
  Rating,
  Sponsorhip,
  Attestation
}
