// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ICommitmentBuilderSystem {
  function registerCommitment() external returns (bytes32);

  function addDescription(bytes32 id, string memory desc) external;

  function addDeadline(bytes32 id, uint32 deadline) external;

  function addPhotoSubmissionRequirement(bytes32 id, string memory proofDescription) external;

  function makeAttestable(bytes32 id, uint32 attestionPeriodDuration) external;

  function activate(bytes32 id) external;

  function registrationHelper(
    string memory desc,
    uint32 deadline,
    string memory proofDescription,
    uint32 attestionPeriodDuration
  ) external returns (bytes32);
}
