// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ICommitmentBuilderSystem {
  function createCommitment(bytes32 id) external;

  function addDescription(bytes32 entity, string memory desc) external returns (bytes32);
}
