// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ICommitmentCreationSystem {
  function addDescription(uint32 entity, string memory desc) external returns (uint32);
}
