// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ICommitmentCheckInSystem {
  function markComplete(bytes32 id) external;

  function markCompleteWithProof(bytes32 id, string memory proofUri) external;
}
