// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ICommitmentCompletionSystem {
  function markComplete(bytes32 id) external;

  function completeWithProof(bytes32 id, string memory proofUri) external;

  function finalize(bytes32 id) external;
}
